### ISSUE TITLE
Colors seem to be off on Atom Material Dark?

### ISSUE THREAD

**Issue by jamby** [HarlemSquirrel/language-haml#70]
So I'm using this package along with Atom Material theme and Atom Material Dark syntax.

Seems like the colors don't color correctly on classes, ids, and other various things and it blends together too much with regular words.

![image](https://user-images.githubusercontent.com/250728/29828457-bfcf7bac-8caa-11e7-8d2d-fdfc3ca28185.png)

**Comment by ezekg** [comment]
This looks like an issue with the syntax theme, not this package. I no longer use Atom, but feel free to dig in and submit a pull request if you think this is indeed an issue and I'll get it merged.

**Comment by darrenterhune** [comment]
I would also say that's the themes problem for sure, not this package. This package is simply a language package. If you like dark themes, try:

UI Theme: Atom Dark
Syntax Theme: Solarized Dark

It's really awesome with haml 😉
