### ISSUE TITLE
Looking for maintainer(s)

### ISSUE THREAD

**Issue by ezekg** [HarlemSquirrel/language-haml#71]
I no longer use Atom. Please comment below if you are interested in taking over this package.

**Comment by HarlemSquirrel** [comment]
I use Atom daily but have not done much with packages. I'd love to help out though!

**Comment by ezekg** [comment]
Thanks, @HarlemSquirrel. Added you as a collaborator. What is your npm username? I can give you publish access if you'd like that as well.

**Comment by HarlemSquirrel** [comment]
Thanks, @ezekg ! My npm username is the same. https://www.npmjs.com/~harlemsquirrel

**Comment by HarlemSquirrel** [comment]
@ezekg I just realized you asked for my `apm` username not `npm`. Duh! It is also HarlemSquirrel.
https://atom.io/users/HarlemSquirrel

**Comment by ezekg** [comment]
Could you delete your fork of this repo so that I can transfer ownership? Apparently if I transfer the repo to you, `apm` will follow suite.

**Comment by HarlemSquirrel** [comment]
@ezekg OK I just deleted my fork.

**Comment by ezekg** [comment]
Sweet. Sent a transfer request. You should be able to publish a new version with `apm publish {major|minor|patch}` after you accept. Thanks again for helping out! 😃

**Comment by HarlemSquirrel** [comment]
Since we have two commits in I'm going to give it a try and release a new patch version.

**Comment by HarlemSquirrel** [comment]
@ezekg 
I tagged a new version in here but it doesn't look like I have access through `apm`.
https://atom.io/packages/language-haml

**Comment by ezekg** [comment]
What is the error you're getting?

**Comment by HarlemSquirrel** [comment]
Here's the logs
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'version',
1 verbose cli   '0.25.2',
1 verbose cli   '-m',
1 verbose cli   'Prepare %s release' ]
2 info using npm@5.4.2
3 info using node@v8.6.0
4 verbose stack Error: Version not changed, might want --allow-same-version
4 verbose stack     at persistVersion (/usr/lib/node_modules/npm/lib/version.js:96:16)
4 verbose stack     at /usr/lib/node_modules/npm/lib/version.js:50:7
4 verbose stack     at /usr/lib/node_modules/npm/lib/version.js:125:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:514:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
5 verbose cwd /home/hs/code/language-haml
6 verbose Linux 4.13.3-1-ARCH
7 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "version" "0.25.2" "-m" "Prepare %s release"
8 verbose node v8.6.0
9 verbose npm  v5.4.2
10 error Version not changed, might want --allow-same-version
11 verbose exit [ 1, true ]
/home/hs/.npm/_logs/2017-10-03T17_17_04_077Z-debug.log (END)
```

**Comment by HarlemSquirrel** [comment]
I just saw the package.json update. I'll try again

**Comment by HarlemSquirrel** [comment]
I think the issue is that I manually updated `package.json` but `apm publish --help` indicates that apm does this for me. 

> If a new version or version increment is specified, then a new Git tag is
created and the package.json file is updated with that new version before
it is published to the apm registry.

**Comment by ezekg** [comment]
Yeah, `apm` will update the version for you. I would revert that commit and try again.

**Comment by ezekg** [comment]
Looks like you already figured it out. Sweet!

**Comment by HarlemSquirrel** [comment]
@ezekg Yup that's what I did and it seems to have worked. Atom now shows the update is ready. 
Thank you!

**Comment by ezekg** [comment]
No problem! 👍
