### ISSUE TITLE
Getting Internal Server Error 500 when trying to install

### ISSUE THREAD

**Issue by gaelant** [HarlemSquirrel/language-haml#79]
Hey all - cannot install this ATOM plug-in without getting an error:

> Installing “language-haml@0.31.1” failed.Hide output…
> Unable to download https://www.atom.io/api/packages/language-haml/versions/0.31.1/tarball: 500 Internal Server Error

I am running on MACOSX High Sierra.

**Comment by HarlemSquirrel** [comment]
What version of Atom are you using? 
Could you try the following to see if you can download the tarball?

```
curl --head https://www.atom.io/api/packages/language-haml/versions/0.31.1/tarball
```

**Comment by HarlemSquirrel** [comment]
@gaelant Are you still having this issue?

**Comment by gaelant** [comment]
Nope, apologies for my lack of response.
