### ISSUE TITLE
Could you add .inky-haml extentsion to the filetype list?

### ISSUE THREAD

**Issue by bo-oz** [HarlemSquirrel/language-haml#81]
Or is this somthing I can configure myself? Would be great to add Inky-Haml support.

**Comment by HarlemSquirrel** [comment]
I'm not familiar with [Inky-Haml](https://github.com/zurb/inky-rb) but it sounds fun! 

Does syntax highlighting work if you select Haml manually in Atom?

**Comment by bo-oz** [comment]
If I change the file type to Haml, syntax highlighting works like a charm. Only that won’t render the template correctly in rails. So it would be nice if you could target additional file types or at least .inky-haml!

**Comment by HarlemSquirrel** [comment]
[v0.32.1 ](https://github.com/HarlemSquirrel/language-haml/releases/tag/v0.32.1) should have this working now.

**Comment by bo-oz** [comment]
You are the man! Thanks a million. Makes my life so much easier 👍
